<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
	<div class="container mt-5">
		<?php if (isset($downloadFilePath)): ?>
		<img src="<?php echo $downloadFilePath; ?>" class="img-thumbnail img-fluid" style="width: 150px; height: 150px;">
		<?php endif; ?>
		<pre>
			<?php print_r($inputData); ?>
		</pre>
	</div>
</body>
</html>